[NUI] Revert "[NUI] Add WebAuthDisplayQR and Response for QR code passkey in WebView"
This reverts commit 06d9c59788af846e5e6a3b3a2d1f7c0744acd2d2.

- chromium web engine update is required
- fix gbs build error : dali-extension/web-engine-chromium/tizen-web-engine-chromium.cpp:867:3: error: 'ewk_view_webauthn_cancel' was not declared in this scope
[  285s]   867 |   ewk_view_webauthn_cancel(mWebView);
[  285s]       |   ^~~~~~~~~~~~~~~~~~~~~~~~