[Connection] Fix crash
Fix crash with error message "Unhandled Exception:
System.InvalidOperationException: An attempt was
made to transition a task to a final state when it had already
completed".
It causes by calling SetResult() after SetException().
https://msdn.microsoft.com/ko-kr/library/dd449202(v=vs.110).aspx

Change-Id: I9e1c98d3507939e433f4fce5f8436459f137e629
Signed-off-by: Cheoleun Moon <chleun.moon@samsung.com>