[Bluetooth] Fix BluetoothDevice converting issue (#4176)
* Fix unhandled exception in GetBondedDevices() (#2485)

I/DOTNET_LAUNCHER (P 2613, T 2617): Unhandled exception.
I/DOTNET_LAUNCHER (P 2613, T 2617): System.Runtime.InteropServices.COMException (0x8007007A):
The data area passed to a system call is too small.
I/DOTNET_LAUNCHER (P 2613, T 2617):  (0x8007007A)
I/DOTNET_LAUNCHER (P 2613, T 2617):    at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src,
IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevices()
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevices()
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.Tests.BluetoothAdapterTests.GetBondedDevices_RETURN_LIST_OF_DEVICES()
in /var/lib/jenkins/jobs/CsharpTCT/TCT_6.0/api/tct-suite-vs/Tizen.Bluetooth.Manual.Tests/testcase/TSBluetoothAdapter.cs:line 435
I/DOTNET_LAUNCHER (P 2613, T 2617): Fatal error.
I/DOTNET_LAUNCHER (P 2613, T 2617): Internal CLR error. (0x80131506)
I/DOTNET_LAUNCHER (P 2613, T 2617): DLOG_ERROR_NOMSG
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Interop+Bluetooth.GetBondedDevices(BondedDeviceCallback, IntPtr)
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevices()
I/DOTNET_LAUNCHER (P 2613, T 2617):    at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevices()

Change-Id: I04a0a89d75dc973a752950c9274b80d9988a11ed
Signed-off-by: Anupam Roy <anupam.r@samsung.com>

Co-authored-by: Anupam Roy <anupam.r@samsung.com>

* Fix BluetoothDevice.Name converting issue (#2498)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

* Fix unhandled exception in GetBondedDevice() (#2514)

Device is not bonded : System.NullReferenceException: Object reference not set to an instance of an object.
    at System.SpanHelpers.IndexOf(Byte& searchSpace, Byte value, Int32 length)
    at System.String.Ctor(SByte* value)
    at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr)
    at Tizen.Network.Bluetooth.BluetoothUtils.ConvertStructToDeviceClass(BluetoothDeviceStruct device)
    at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevice(String address)
    at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevice(String address)

Signed-off-by: DoHyun Pyun <dh79.pyun@samsung.com>

* GetBondedDevice converting issue (#2517)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>
Co-authored-by: dh79pyun <31202060+dh79pyun@users.noreply.github.com>

* Fix BluetoothDevice data converting issue (#2887)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

* Add device name null check logic (#3084)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

* Add log for converting devcie info (#3303)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

* Fix DeviceName converting issue (#3351)

Signed-off-by: Wootak Jung <wootak.jung@samsung.com>

* Fix the crash in GetBondedDevices API (#1643)

The manufacture data can be filled without NULL termination.
Because it is the byte array type. So we should define it as
IntPrt instead of string to avoid the buffer overflow.

Exception !!!: System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small.
at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkListElement& pCleanupWorkList)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.GetBondedDevices()
at Tizen.Network.Bluetooth.BluetoothAdapter.GetBondedDevices()

Signed-off-by: DoHyun Pyun <dh79.pyun@samsung.com>

* Add NULL check logic for Marshal.PtrToStringAnsi (#1657)

This patchset is to avoid ArgumentNullException error. There are some
cases to come NULL variable from Native API.

BluetoothAdapterImpl.cs: RegisterDiscoveryStateChangedEvent(258) > Discovery state changed callback is called
Unhandled exception.
System.ArgumentNullException: Value cannot be null. (Parameter 'ptr')
at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr ptr, Int32 len)
at Tizen.Network.Bluetooth.BluetoothUtils.ConvertStructToDiscoveredDevice(BluetoothDiscoveredDeviceStruct structDevice)
at Tizen.Network.Bluetooth.BluetoothAdapterImpl.<RegisterDiscoveryStateChangedEvent>b__45_0(Int32 result, BluetoothDeviceDiscoveryState state, IntPtr deviceInfo, IntPtr user

Signed-off-by: DoHyun Pyun <dh79.pyun@samsung.com>

Co-authored-by: dh79pyun <31202060+dh79pyun@users.noreply.github.com>
Co-authored-by: Anupam Roy <anupam.r@samsung.com>